console.log("====================Ques 2====================");
var sweety = "Sweety";
var cutie = "Cutie";
console.log("before swap Sweety:" ,sweety);
console.log("before swap Cutie:" ,cutie);
var temp = null;
temp = sweety;
console.log("temo :",temp);
sweety = cutie;
console.log("After swap Sweety:" ,sweety);
cutie = temp;
console.log("After swap Cutie:" ,cutie);

//=============Ques 2===============================
console.log("====================Ques 2====================");
var num1 = 100;
var num2 = 200;
var num3 = 300;
console.log("num1 : ",num1);
console.log("num2 : ",num2);
console.log("num3 : ",num3);
var temp = null;
temp = num1;
num1 = num2;
console.log("After swap num1 ~ num2", num1,"~",num2);
num2=num3;
console.log("After swap num2 ~ num3", num2,"~",num3);
num3=temp;
console.log("After swap num3 ~ num1", num3,"~",num1);
console.log("After swap num1 ~ num2 ~ num3", num1,"~",num2,"~",num3);